/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author Mauricio
 */
import dao.DAOHabitacion;
import dao.DAOReserva;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.List;
import modelo.Cliente;
import modelo.Reserva;

public class HistorialClienteForm extends JFrame {

    private JTable tablaHistorial;
    private DefaultTableModel modeloTabla;
    private Cliente cliente;
    private DAOReserva daoReserva;
    private DAOHabitacion daoHabitacion;

    public HistorialClienteForm(Cliente cliente) {
        this.cliente = cliente;
        this.daoReserva = new DAOReserva();
        this.daoHabitacion = new DAOHabitacion();

        setTitle("Historial de Reservas del Cliente");
        setSize(800, 450);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        modeloTabla = new DefaultTableModel(new String[]{
    "ID", "Habitación", "Fecha Reserva", "Fecha Estadía", "Precio Pagado", "Estado"
}, 0) {
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};

        tablaHistorial = new JTable(modeloTabla);
        JScrollPane scroll = new JScrollPane(tablaHistorial);
        add(scroll, BorderLayout.CENTER);

        cargarHistorial();

       tablaHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int fila = tablaHistorial.rowAtPoint(evt.getPoint());
        if (fila != -1) {
            String estado = (String) modeloTabla.getValueAt(fila, 5);
            System.out.println("Estado de reserva seleccionada: " + estado);  // Para debug

            if (estado.equalsIgnoreCase("Activa")) { // Cambié de "Vigente" a "Activa"
                int confirmar = JOptionPane.showConfirmDialog(
                    HistorialClienteForm.this,
                    "¿Deseas cancelar esta reserva?",
                    "Confirmar cancelación",
                    JOptionPane.YES_NO_OPTION
                );
                if (confirmar == JOptionPane.YES_OPTION) {
                    int idReserva = (int) modeloTabla.getValueAt(fila, 0);
                    boolean exito = daoReserva.cancelarReserva(idReserva);
                    if (exito) {
                        // Actualizar habitación a disponible
                        int idHabitacion = daoReserva.obtenerIdHabitacionPorReserva(idReserva);
                        daoHabitacion.actualizarEstado(idHabitacion, "Disponible");

                        JOptionPane.showMessageDialog(HistorialClienteForm.this, "Reserva cancelada con éxito.");
                        cargarHistorial();
                    } else {
                        JOptionPane.showMessageDialog(HistorialClienteForm.this, "Error al cancelar reserva.");
                    }
                }
            }
        }
    }
});
    }

    private void cargarHistorial() {
    modeloTabla.setRowCount(0); // limpia la tabla

    List<Reserva> reservas = daoReserva.listarReservasPorCliente(cliente.getId());
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    for (Reserva r : reservas) {
        // Puedes usar directamente el ID de habitación o buscar el nombre si quieres
        String habitacion = "Habitación #" + r.getIdHabitacion(); // o usa daoHabitacion.obtenerNombrePorId(...)

        modeloTabla.addRow(new Object[]{
            r.getId(),
            habitacion,
            r.getFechaReserva().format(formato),
            r.getFechaEstadia().format(formato),
            String.format("$ %.2f", r.getPrecioPagado()),
            r.getEstado()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
